apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9404"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/cluster: databus-cluster
  name: databus-strimzi-kafka-exporter
  namespace: databus
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9404
    protocol: TCP
    targetPort: 9404
  selector:
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/cluster: databus-cluster
  