apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    apicur.io/name: apicurio-registry-operator
    apicur.io/type: operator
    apicur.io/version: 1.0.0
  name: apicurio-registry-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apicurio-registry-operator-role
subjects:
- kind: ServiceAccount
  name: apicurio-registry-operator
  namespace: {{ .Release.Namespace  }}
