apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    apicur.io/name: apicurio-registry-operator
    apicur.io/type: operator
    apicur.io/version: 1.0.0
  name: apicurio-registry-operator-leader-election-role
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
