apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    apicur.io/name: apicurio-registry-operator
    apicur.io/type: operator
    apicur.io/version: 1.0.0
  name: apicurio-registry-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apicurio-registry-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: apicurio-registry-operator
